name: learn-github-actions
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: My first job
    steps:
      - run: echo Step 1 Complete
      - run: echo Step 2 Complete
  job2:
    runs-on: ubuntu-latest
    uses: mscoutermarsh/cowsays-action@v1
    with:
      # What does the cow say?
      text: # optional, default is Ship it!!!!!
      # Color of your cow
      color: # optional, default is white
          
      
